### ISSUE TITLE
New type error after fix  #1085

### ISSUE THREAD

**Issue by rleecn** [catfan/Medoo#1089]
**Information**
- Version of Medoo:2.1.9
- Version of PHP:8.1
- Type of Database (MySQL, MSSQL, SQLite...):MySQL
- System (Liunx|Windows|Mac):Linux

**Describe the Problem**
For fix the issue #1085 ,make the field not defined will be converted to String type,like Int...which real need Int value and not String value, please make a default logic that will not be converted.

**Detail Code**
The detail code you are using causes the problem.
```php
// Write your PHP code here

```

**Expected output**
A clear and concise description of what output you expected.

**Comment by scr4bble** [comment]
We are having the same issue. I noticed some logic stopped working in our app because of changed types returned from medoo. I guess there will be many places now where this got broken.
We upgraded from 2.1.4 to 2.1.9 and the following code
```
$this->select('user_id', ['group_id' => $group_id, 'group_type' => $group_type]);
```
started returning array of strings instead of integers.
user_id is defined as int in our MySQL database.

If it was intended, please don't do such changes without using new major version.
Could you please look into it as soon as possible? I will downgrade the version back in the meantime.

**Comment by catfan** [comment]
@hzbbcc @scr4bble I have fixed this issue on 802251e. Would you try that and see if the problem is resolved?

**Comment by scr4bble** [comment]
Yes, it seems to work in 802251e - at least the one case that I mentioned above.
I had some difficulties trying a specific commit though so I hope I tested it correctly.
(had to add the repo into "repositories" in composer.json and use `composer require catfan/medoo:dev-master#802251e`)

**Comment by catfan** [comment]
@scr4bble OK. The v2.1.10 version with this fix is released. https://github.com/catfan/Medoo/releases/tag/v2.1.10
