### ISSUE TITLE
LIMIT in a UPDATE query

### ISSUE THREAD

**Issue by omphteliba** [catfan/Medoo#138]
I am trying to get a mysql query like this:

``` sql
 UPDATE users SET tobefollowed =1 WHERE (
 screen_name LIKE '%and%' OR description LIKE '%and%'
 ) LIMIT 100 
```

And tried it like that:

``` php
$database->update("users", ["tobefollowed"=>"1"], [
                            "LIKE" => [
                                "OR" => [
                                    "screen_name" => [$keyword],
                                    "description" => [$keyword]
                                ]
                            ],
                            "LIMIT" => [100]
                    ]);
```

But with this i only get this query:

``` sql
UPDATE "users" SET "tobefollowed" = '1' WHERE (
"screen_name" LIKE '%and%' OR "description" LIKE '%and%')
```

The Medoo source has code for LIMIT, but i have no idea why it didn't work.

**Comment by KIRANMAGNAQUEST** [comment]
Thankyou..

**Comment by SteveJobzniak** [comment]
For those wondering why there is no LIMIT, I have the answer:

Medoo ITSELF supports LIMIT in the update() function. You just have to do ['LIMIT' => 1] in the $where parameter.

The problem is that PHP has compiled the built-in SQLite engine WITHOUT SUPPORT for LIMIT in UPDATE / DELETE.

https://www.sqlite.org/lang_update.html

> "If SQLite is built with the SQLITE_ENABLE_UPDATE_DELETE_LIMIT compile-time option then the syntax of the UPDATE statement is extended with optional ORDER BY and LIMIT clauses".

Seems pretty stupid that PHP doesn't compile SQLite with that feature, but there you have the answer!

It's possible to recompile SQLite in PHP but that's a total hell, so I guess I will live with PHP's SQLite wastefully searching every database row for matching columns instead of stopping as soon as it has found one... Sigh.
