### ISSUE TITLE
LIMIT for Update ?

### ISSUE THREAD

**Issue by Snoop** [catfan/Medoo#146]
I can not get the LIMIT Parameter to work with the UPDATE query.

php 5.3

$result = $database->update("test", array(
	"active" => 1
),array(
	"AND" => array(
		"var1" => 0,
		"var2" => 0
	)
),array(
	"LIMIT" => 1
	)
));

It does not work. It is not supported?

**Comment by catfan** [comment]
No limit for UPDATE

**Comment by SteveJobzniak** [comment]
For those wondering why there is no LIMIT, I have the answer:

Medoo ITSELF supports LIMIT in the update() function. You just have to do ['LIMIT' => 1] in the $where parameter.

The problem is that PHP has compiled the built-in SQLite engine WITHOUT SUPPORT for LIMIT in UPDATE / DELETE.

https://www.sqlite.org/lang_update.html

> "If SQLite is built with the SQLITE_ENABLE_UPDATE_DELETE_LIMIT compile-time option then the syntax of the UPDATE statement is extended with optional ORDER BY and LIMIT clauses".

Seems pretty stupid that PHP doesn't compile SQLite with that feature, but there you have the answer!

It's possible to recompile SQLite in PHP but that's a total hell, so I guess I will live with PHP's SQLite wastefully searching every database row for matching columns instead of stopping as soon as it has found one... Sigh.
