### ISSUE TITLE
Medoo doesn't use prepared statements

### ISSUE THREAD

**Issue by buar** [catfan/Medoo#264]
Medoo will be vulnerable to SQL injection with some configurations.

**Comment by smartclash** [comment]
@catfan I think this issue should be reopened. SQL injections are the basic problems because a website gets hacked. Actually digging through the code, i found you are using `PDO::quote()`. It is good. But php recommends more.

A per PHP website : 

> If you are using quote() to build SQL statements, you are strongly recommended to use PDO::prepare() to prepare SQL statements with bound parameters instead of using PDO::quote() to interpolate user input into an SQL statement. Prepared statements with bound parameters are not only more portable, more convenient, immune to SQL injection, but are often much faster to execute than interpolated queries, as both the server and client side can cache a compiled form of the query.

For more information, you can actually find relative links in google.
* http://stackoverflow.com/questions/19817108/sanitising-user-input-with-medoo

**Comment by catfan** [comment]
@smartclash Firstly, there is no big different between using `PDO::quote` and prepare statement for SQL injection. They are doing the same thing for handling data. If you think it is too dangerous because it didn't use prepare(). That's wrong.

Secondly, I admit that prepare statement has some more advantage. So, Medoo is reconstructed using `PDO::prepare()` and provide more advanced feature on develop branch now, and will be released soon.

**Comment by smartclash** [comment]
@catfan Awesome. +1

**Comment by vesamet** [comment]
Hi there ! Out of curiosity, have this been implemented ?
I'm sanitizing everything i throw at Medoo, but i wonder if i actually need to.

**Comment by catfan** [comment]
@vesamet This issue is closed. Medoo is reconstructed using `prepare()` for binding value since v1.4.

**Comment by Chamberlainfrancis** [comment]
@catfan  So its safe to say 

```
$database->insert("account", [
	"user_name" => "foo"
]);
```
without having to PDO bindParams
just curious!

**Comment by philwu** [comment]
> @catfan So its safe to say
> 
> ```
> $database->insert("account", [
> 	"user_name" => "foo"
> ]);
> ```
> 
> without having to PDO bindParams
> just curious!

If you read the code you will find that Medoo does prepare and bindParams for you.
