### ISSUE TITLE
error on demo with sqlite: no such table: account

### ISSUE THREAD

**Issue by joernroeder** [catfan/Medoo#265]
Hey,
i've tried to run the demo with a fresh sqlitedb but got the `"no such table: account"` error and didn't found a `create(Table)` method in the docs. How can i create my tables?
thanks in advance!

**Comment by 2doous** [comment]
use medoo->query(create........);

**Comment by catfan** [comment]
You have to create the database by yourself.

Medoo don't provide `create` method because it only run a time for most case, and for most of time, using some database management tool like **MySQL Administrator**, to generate the create table query and then use the `$database->query()` or `exec()` will be the better choice.

**Comment by joernroeder** [comment]
thanks for the infos guys! I'd recommend to clarify the docs in this case to prevent further noob issues.
