### ISSUE TITLE
 'Undefined property: medoo::$pdo' Line 188

### ISSUE THREAD

**Issue by mr-lanholmes** [catfan/Medoo#297]
exception 'Whoops\Exception\ErrorException' with message 'Undefined property: medoo::$pdo' in C:\Users\User\Desktop\Project\vendor\catfan\medoo\medoo.php:188

How can I solve this?

Thanks.

**Comment by DeeJaVu** [comment]
same issue, @catfan  please help this issue was posted 22 days ago so i cant wait that long for an answers

**Comment by manulaiko** [comment]
Have you got enabled PDO extension?

**Comment by satriyowibowo** [comment]
upgrade from v0.9.8.3 to v1.0
and also have the same problem

**Comment by DeeJaVu** [comment]
yea pdo is enabled

**Comment by SyuTingSong** [comment]
Cannot represent the issue you got. Print the call stack would help.

**Comment by DeeJaVu** [comment]
i dont care anymore i switched to laravel

**Comment by Hiroko103** [comment]
Notice that support for direct initialization has been removed in 1.0.
It means you cannot set the variables inside the medoo.php file.
You should pass the initial variables to the class constructor when creating a medoo instance.

```php
$database = new medoo([
    'database_type' => 'mysql',
    'database_name' => 'name',
    'server' => 'localhost',
    'username' => 'your_username',
    'password' => 'your_password',
    'charset' => 'utf8'
]);
```

**Comment by catfan** [comment]
The info you provided is not sufficient enough. It is hard to make someone to help you.

**Comment by feelsickened** [comment]
Hiroko103 is spot on - The direct initialisation feature has been removed, and will cause issues such as: Fatal error: Call to a member function quote() on a non-object in /home/content/20/10935220/html/engineroom/assets/medoo.php on line 188

I just upgraded from VERSION 0.9.6.2 to VERSION 1.0 and encountered the above error, but initialising when creating a new medoo solved the error.

Sorry to complain, but I prefer direct initialisation, and REQUEST it's return if possible.
As a result of it being removed I have to add $database = new medo (all my database details...) to many many cron jobs. Additionally I much prefer to have the details of my SQL database secure in one file (i.e medoo.php) not many files. Just doesn't seem secure/smart.

ps catfan - i love medoo - you've saved me millions of hours.

**Comment by pwwang** [comment]
I encountered the same issue.
Just post here for someone in need.
This happens mostly because you didn't pass the right `$options` to the constructor. In most case, it's `NULL` if you didn't check it carefully.

In my case, I actually define the `$options` outside a function, and use `global` keyword to bring it to the function. However,it's not expected; it's `NULL`.
http://stackoverflow.com/questions/4074815/why-global-is-null-in-function

The reason why it reports `'Undefined property: medoo::$pdo'` is because when `$options` is not an `array`, the constructor will return false [medoo.php:L57](https://github.com/catfan/Medoo/blob/master/medoo.php#L57) and the follow PDO initialization is not called.
