### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by xensor** [catfan/Medoo#309]
[code]
  $this->db->select("news", ["[>]news_cats" => ["cat_id" => "id"]], [
            "news.*",
            "news_cats.name"
        ], [

            "ORDER" => "news.id DESC",
            "LIMIT" => [$start,$limit]
        ]);

[/code]

see this is my issue.

its not showing properly.

so can someone help me out with this code. please

it would be thankful. I am going insane with how its not giving results. 

this is what i am getting when i try it:

[code]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."author","news"."title","news"."postdate","news"."cat_id","news"."id","news_cat' at line 1 
[/code]

**Comment by xensor** [comment]
I got it to work. but can someone still explain to me how it works better. the docs isn't really friendly.

**Comment by SyuTingSong** [comment]
The filed `author` was not used in your PHP code. Maybe the error caused by other query.

Please add debug method `$this->db->debug()->select(...` to print the SQL code generated by Medoo to debug.

BTW, you can use [Markdown](https://guides.github.com/features/mastering-markdown) 4-space-indent  to present code block.

**Comment by catfan** [comment]
Do not use `news.*` for table joining.
