### ISSUE TITLE
Join problem

### ISSUE THREAD

**Issue by adminko-svk** [catfan/Medoo#357]
How can I use JOIN with static values?
The second (joining) table has column "xyz" and I need to create JOIN query where "xyz" = 123

Thank you.

**Comment by adminko-svk** [comment]
I found similar problem here https://github.com/catfan/Medoo/issues/167
Can you please add the modifier `[$]` to the next release of Medoo

**Comment by chrisaybar** [comment]
I ran into the same problem, but came up with a quick solution for v1.0.2 while the developers find a neat way to add support for this.

Note: this quick hack is only meant to get you through the problem if you're in a bind.

Step 1, change line 595 to the following:

BEFORE:

```php
	'"' . (isset($match[ 5 ]) ? $match[ 5 ] : $match[ 3 ]) . '"."' . $value . '"';
```php

AFTER:

```php
	((substr($value, 0, 4) == '[SV]') ? substr($value, 4) : '`' . (isset($match[ 5 ]) ? $match[ 5 ] : $match[ 3 ]) . '`.`' . $value . '`');
```php

Step 2, add temporary support for denoting a static value by preceeding your join value with "[SV]". For example, in your table join, instead of using something like [ 'fieldName' => 'fieldValue' ] use this instead: 

```php
[ 'fieldName' => '[SV]fieldValue' ]
```php

Hope this helps.
