### ISSUE TITLE
Error near "," when multiple insert in sqlite db

### ISSUE THREAD

**Issue by Drive4ik** [catfan/Medoo#533]
Error near "," when multiple insert in sqlite db.
sqlite 3.7.7.1 
php 5.3.27
Medoo 1.2.1

**Comment by Drive4ik** [comment]
Can you investigate this issue?

**Comment by catfan** [comment]
Perhaps you need to update your SQLite to 3.7.11+ for multiple insertion.

Because v1.2 is optimized the multiple insertion statement with executing only one query `INSERT INTO xxx VALUES(xxx), (xxx), (xxx)`.

http://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database/1609688#1609688
