### ISSUE TITLE
two objects with same alias not possible

### ISSUE THREAD

**Issue by hdrodel** [catfan/Medoo#749]
Hey, i ran into the following problem:

I'm tying to get a start and an endadress from the Database . when getting the data from the database i would like to put it into the following structure:

`'startAdress'=>[
       'startNote(info)',
	'adresses.street',
	'startAdrNr(nr)',
	'adresses.zip(zip)',
	'adresses.place(place)'
	],
'endAdress'=>[
	'endNote(info)',
	'eAdr.street(street)',
	'endAdrNr(nr)',
	'eAdr.zip(zip)',
	'eAdr.place(place)'
],`

if i do so, the start and end address become the same. Is there a way to resolve that? 

edit: 

I just realized that this may also be a join issue. I have a database called addresses in this i store each address with the place and zip and join them on the id. I need to join them twice for the start address and the end address. What i tried to do is the following. 

`$data = $database->select('orders',[
'[>]adresses'=>['startAdress'=>'id'],
'[>]adresses(eAdr)'=>['endAdress'=>'id'],
        ]....`

**Comment by woubuc** [comment]
I'm running into the same issue. I have the following query:

```php
$db->select('items',
  ['[>]users' => ['owner' => 'id']],
  [
    'items.id',
    'items.name',
    'owner' => ['users.id (id)', 'users.name (name)']
  ]
);
```

Expected output (JSON):
```json
{
  "id": 1,
  "name": "item name",
  "owner": {
    "id": 2,
    "name": "user name"
  }
}
```

Actual output (JSON):
```json
{
  "id": 2,
  "name": "user name",
  "owner": {
    "id": 2,
    "name": "user name"
  }
}
```
So it will use the value of the last field with the same name for all fields with that name.

I've noticed when using debug mode, that the SQL query adds these alias in the query (`users.id AS id`). It seems to me that this would be fixed by selecting the fields as their actual name (`users.id`) and then mapping them to the data model when the response comes back.

**Comment by catfan** [comment]
That's because the PDO layer or database engine will return fetched data as one-dimensional array that the alias column name will be overridden.

But right now, I have a new idea to make this work possible. It may be supported on next version.

**Comment by ggedde** [comment]
Same issue, 
@catfan any news on the new idea.

Currently, I find the Data Mapping an awesome way to organize joins, but because many of the fields use the same key it sort of makes data mapping not really usable for me.

Here is what I would like to do:
`$db->select('users',
  ['[>]accounts' => ['account_id' => 'id']],
  [
    'users.id',
    'users.name',
    'account' => ['accounts.id', 'accounts.name']
  ]
);`
But instead I have to end up doing:
`$db->select('users',
  ['[>]accounts' => ['account_id' => 'id']],
  [
    'users.id',
    'users.name',
    'account' => ['accounts.id(account_id)', 'accounts.name(account_name)']
  ]
);`
And if I am going to do that then I might as well just do:
`$db->select('users',
  ['[>]accounts' => ['account_id' => 'id']],
  [
    'users.id',
    'users.name',
    'accounts.id(account_id)',
    'accounts.name(account_name)'
  ]
);`

However, I would rather stick with the first method.
Thanks

**Comment by cheap-glitch** [comment]
Any updates on this ? Would love to have this feature!
