### ISSUE TITLE
Having PHPDocs ?

### ISSUE THREAD

**Issue by superdeeid** [catfan/Medoo#831]
Hi all,

**medoo 1.6.1**
God i love medoo (using since 3 years now) for mySQL/MsSQL.
Is there any reason why there is no PHPDocs on functions ? Could be a great to have it since IDE rely on that too... And for us too. My 2 cents.

Regards,

**Comment by catfan** [comment]
Because Medoo is using multiple style in one function.

For example, `select()` is having `select($table, $columns, $where)` and `select($table, $join, $columns, $where)` call.

And most of parameter type are mixed and with special syntax (`column[+]`, `column (alias) [Int]` and more).

Additionally, the initialization is using array key to configure that is with a lot of options.

In current, IDE with PHPDocs is not good enough for showing tips for that. The best way is still reading our official docs yet.
